<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Bmi_summary_report_handler
{
    private $ci;

    public function __construct()
    {
        $this->ci = get_instance();
    }

    public function generate($all_data, $branch_name, $first_day, $last_day)
    {
        $this->ci->load->library('excel');

        $style = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            )
        );

        $object = new PHPExcel();

        $date = DateTime::createFromFormat('Y-m-d', $first_day);
        $from_f = $date ? $date->format('d/m/Y') : $first_day;
        $date = DateTime::createFromFormat('Y-m-d', $last_day);
        $to_f = $date ? $date->format('d/m/Y') : $last_day;

        $sheet_index = 0;
        foreach ($all_data as $bmi) {
            $employee = $bmi['employee'];
            if ($sheet_index > 0) {
                $object->createSheet();
            }
            $object->setActiveSheetIndex($sheet_index++);
            $object->getDefaultStyle()->applyFromArray($style);

            $sheet = $object->getActiveSheet();
            $sheet->setTitle(substr((string)$employee->special_id, 0, 30));

            $name_columns = array('Name', 'Employee ID', 'Department', 'Position', 'Branch', 'From', 'To', 'Generated at', 'Generated by');
            $table_columns = array('Date', 'Acting', 'Shift', 'In', 'Out', 'WD', 'OT', 'Sun', 'PH < 8', 'PH > 8', 'TA', 'MA', 'CA', 'SPA', 'ACA', 'FL Inc', 'C/wash', 'M/ope', 'Shift1', 'Shift2', 'Shift3');

            $column = 0;
            foreach ($name_columns as $field) {
                $sheet->setCellValueByColumnAndRow($column, 1, $field);
                $sheet->getStyleByColumnAndRow($column, 1)->getFont()->setBold(true);
                $column++;
            }

            $sheet->setCellValueByColumnAndRow(0, 2, isset($employee->first_name) ? $employee->first_name : '');
            $sheet->setCellValueByColumnAndRow(1, 2, isset($employee->special_id) ? $employee->special_id : '');
            $sheet->setCellValueByColumnAndRow(2, 2, isset($employee->department) ? $employee->department : '');
            $sheet->setCellValueByColumnAndRow(3, 2, isset($employee->position) ? $employee->position : '');
            $sheet->setCellValueByColumnAndRow(4, 2, $branch_name);
            $sheet->setCellValueByColumnAndRow(5, 2, $from_f);
            $sheet->setCellValueByColumnAndRow(6, 2, $to_f);
            $sheet->setCellValueByColumnAndRow(7, 2, date('d/m/Y H:i:s'));
            $sheet->setCellValueByColumnAndRow(8, 2, 'Queue Worker');

            $column = 0;
            foreach ($table_columns as $field) {
                $sheet->setCellValueByColumnAndRow($column, 4, $field);
                $sheet->getStyleByColumnAndRow($column, 4)->getFont()->setBold(true);
                $column++;
            }

            $row = 5;
            if (!empty($bmi['dates'])) {
                foreach ($bmi['dates'] as $d) {
                    $clock = (isset($d->clockings) && is_array($d->clockings) && isset($d->clockings[0])) ? $d->clockings[0] : null;
                    $sheet->setCellValueByColumnAndRow(0, $row, isset($clock->day_f) ? $clock->day_f : (isset($d->date_string) ? $d->date_string : ''));
                    $sheet->setCellValueByColumnAndRow(1, $row, isset($d->acting_code) ? $d->acting_code : '');
                    $sheet->setCellValueByColumnAndRow(2, $row, isset($d->shift_name) ? $d->shift_name : '');
                    $sheet->setCellValueByColumnAndRow(3, $row, isset($d->first_in) ? $d->first_in : '');
                    $sheet->setCellValueByColumnAndRow(4, $row, isset($d->last_out) ? $d->last_out : '');
                    $sheet->setCellValueByColumnAndRow(5, $row, isset($d->days) ? $d->days : 0);
                    $sheet->setCellValueByColumnAndRow(6, $row, isset($d->bmi_ot) ? $d->bmi_ot : 0);
                    $sheet->setCellValueByColumnAndRow(7, $row, isset($d->bmi_ot_sunday) ? $d->bmi_ot_sunday : 0);
                    $sheet->setCellValueByColumnAndRow(8, $row, isset($d->bmi_ph_1) ? $d->bmi_ph_1 : 0);
                    $sheet->setCellValueByColumnAndRow(9, $row, isset($d->bmi_ph_2) ? $d->bmi_ph_2 : 0);
                    $sheet->setCellValueByColumnAndRow(10, $row, isset($d->bmi_ta_final) ? $d->bmi_ta_final : 0);
                    $sheet->setCellValueByColumnAndRow(11, $row, isset($d->bmi_ma_final) ? $d->bmi_ma_final : 0);
                    $sheet->setCellValueByColumnAndRow(12, $row, isset($d->bmi_ca_final) ? $d->bmi_ca_final : 0);
                    $sheet->setCellValueByColumnAndRow(13, $row, isset($d->bmi_spa_final) ? $d->bmi_spa_final : 0);
                    $sheet->setCellValueByColumnAndRow(14, $row, isset($d->bmi_aca_final) ? $d->bmi_aca_final : 0);
                    $sheet->setCellValueByColumnAndRow(15, $row, isset($d->bmi_fl_final) ? $d->bmi_fl_final : 0);
                    $sheet->setCellValueByColumnAndRow(16, $row, isset($d->bmi_cw_final) ? $d->bmi_cw_final : 0);
                    $sheet->setCellValueByColumnAndRow(17, $row, isset($d->bmi_mo_final) ? $d->bmi_mo_final : 0);
                    $sheet->setCellValueByColumnAndRow(18, $row, isset($d->bmi_shift1_final) ? $d->bmi_shift1_final : 0);
                    $sheet->setCellValueByColumnAndRow(19, $row, isset($d->bmi_shift2_final) ? $d->bmi_shift2_final : 0);
                    $sheet->setCellValueByColumnAndRow(20, $row, isset($d->bmi_shift3_final) ? $d->bmi_shift3_final : 0);
                    $row++;
                }
            }

            foreach (range('A', 'U') as $columnID) {
                $sheet->getColumnDimension($columnID)->setAutoSize(true);
            }
        }

        $object->setActiveSheetIndex(0);

        $xlsx_name = '(' . $branch_name . ') BMI Full Summary - ' . $first_day . ' to ' . $last_day . ' ' . time() . '.xlsx';
        $xlsx_path = FCPATH . 'uploads/summary/' . $xlsx_name;
        $writer = new PHPExcel_Writer_Excel2007($object);
        $writer->save($xlsx_path);

        $zip_name = '(' . $branch_name . ') BMI Full Summary - ' . $first_day . ' to ' . $last_day . ' ' . time() . '.zip';
        $zip_path = FCPATH . 'uploads/summary/' . $zip_name;
        $zip = new ZipArchive();
        if ($zip->open($zip_path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception('Failed to create BMI summary ZIP');
        }
        $zip->addFile($xlsx_path, basename($xlsx_path));
        $zip->close();
        @unlink($xlsx_path);

        return array(
            'status' => 'success',
            'file_path' => $zip_path,
            'file_name' => $zip_name,
            'summary' => array(
                'branch' => $branch_name,
                'period' => array(
                    'from' => $from_f,
                    'to' => $to_f
                ),
                'employee_count' => count($all_data),
                'file_type' => 'zip',
                'generated_at' => date('Y-m-d H:i:s'),
                'generated_by' => 'Queue Worker'
            )
        );
    }
}
