<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Lateness_report_handler
{
    private $load;

    public function __construct($params = array())
    {
        $CI = get_instance();
        $this->load = isset($params['load']) ? $params['load'] : $CI->load;
    }

    public function generate($all_data, $month_rows, $branch_name, $first_day, $last_day, $first_day_formatted, $last_day_formatted)
    {
        $this->load->library('excel');

        $style = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER
            )
        );

        $object = new PHPExcel();
        $name_columns = array('Branch', 'From', 'To', 'Generated at', 'Generated by');
        $table_columns = array('Name', 'Employee ID', 'Lateness Count', 'Lateness Time');

        $month_count = 0;
        foreach ($month_rows as $month_row) {
            if ($month_count == 0) {
                $object->setActiveSheetIndex(0);
                $object->getActiveSheet()->setTitle(substr($month_row['month_name'], 0, 31));
            } else {
                $object->createSheet();
                $object->setActiveSheetIndex($month_count);
                $object->getActiveSheet()->setTitle(substr($month_row['month_name'], 0, 31));
            }

            $object->getActiveSheet()->getDefaultStyle()->applyFromArray($style);

            $column = 0;
            foreach ($name_columns as $field) {
                $object->getActiveSheet()->setCellValueByColumnAndRow($column, 1, $field);
                $object->getActiveSheet()->getStyleByColumnAndRow($column, 1)->getFont()->setBold(true);
                $column++;
            }

            $object->getActiveSheet()->setCellValueByColumnAndRow(0, 2, $branch_name);
            $object->getActiveSheet()->setCellValueByColumnAndRow(1, 2, $month_row['from']);
            $object->getActiveSheet()->setCellValueByColumnAndRow(2, 2, $month_row['to']);
            $object->getActiveSheet()->setCellValueByColumnAndRow(3, 2, date('d/m/Y H:i:s'));
            $object->getActiveSheet()->setCellValueByColumnAndRow(4, 2, 'Queue Worker');

            $column = 0;
            foreach ($table_columns as $field) {
                $object->getActiveSheet()->setCellValueByColumnAndRow($column, 4, $field);
                $object->getActiveSheet()->getStyleByColumnAndRow($column, 4)->getFont()->setBold(true);
                $column++;
            }

            $row = 5;
            foreach ($all_data as $entry) {
                $employee_id = isset($entry['employee_id']) ? (int)$entry['employee_id'] : (isset($entry['id']) ? (int)$entry['id'] : 0);
                $monthly_entry = isset($month_row['rows_by_employee'][$employee_id]) ? $month_row['rows_by_employee'][$employee_id] : array();

                $object->getActiveSheet()->setCellValueByColumnAndRow(0, $row, isset($entry['first_name']) ? $entry['first_name'] : (isset($entry['employee']->first_name) ? $entry['employee']->first_name : ''));
                $object->getActiveSheet()->setCellValueByColumnAndRow(1, $row, isset($entry['special_id']) ? $entry['special_id'] : (isset($entry['employee']->special_id) ? $entry['employee']->special_id : ''));
                $object->getActiveSheet()->setCellValueByColumnAndRow(2, $row, array_key_exists('late_count', $monthly_entry) ? $monthly_entry['late_count'] : null);
                $object->getActiveSheet()->setCellValueByColumnAndRow(3, $row, array_key_exists('lateness_time_deducted', $monthly_entry) ? $this->format_time_value($monthly_entry['lateness_time_deducted']) : null);
                $row++;
            }

            foreach (range('A', 'R') as $columnID) {
                $object->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
            }

            $month_count++;
        }

        $object->setActiveSheetIndex(0);
        $file_name = '(' . $branch_name . ') Lateness Summary - ' . $first_day . ' to ' . $last_day . ' ' . time() . '.xlsx';
        $file_path = $this->build_report_path('lateness', $file_name);
        $writer = new PHPExcel_Writer_Excel2007($object);
        $writer->save($file_path);

        return array(
            'status' => 'success',
            'file_path' => $file_path,
            'file_name' => $file_name,
            'summary' => array(
                'branch' => $branch_name,
                'period' => array(
                    'from' => $first_day_formatted,
                    'to' => $last_day_formatted
                ),
                'employee_count' => count($all_data),
                'file_type' => 'xlsx',
                'generated_at' => date('Y-m-d H:i:s'),
                'generated_by' => 'Queue Worker'
            )
        );
    }

    private function format_time_value($value)
    {
        if ($value === null || $value === '') {
            return null;
        }

        if (is_numeric($value)) {
            $decimal = (float)$value;
            if ($decimal <= 0) {
                return null;
            }

            $minutes = (int)round($decimal * 60);
            $hours = (int)floor($minutes / 60);
            $remaining_minutes = $minutes % 60;
            return sprintf('%02d:%02d', $hours, $remaining_minutes);
        }

        if (is_string($value)) {
            $value = trim($value);
            if ($value === '' || $value === '00:00:00') {
                return null;
            }

            if (preg_match('/^\d{1,2}:\d{2}(:\d{2})?$/', $value)) {
                return substr($value, 0, 5);
            }
        }

        return null;
    }

    private function build_report_path($report_type, $file_name)
    {
        $directory = FCPATH . 'uploads/summary/monthlock/' . trim($report_type, '/\\') . '/';

        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create report directory: ' . $directory);
        }

        return $directory . $file_name;
    }
}
