<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Short_month_lock_report_handler
{
    private $ci;

    public function __construct()
    {
        $this->ci = get_instance();
    }

    public function generate($all_data, $branch_name, $first_day, $last_day, $first_day_formatted, $last_day_formatted, $file_type)
    {
        $file_name = "($branch_name) Short Summary - $first_day to $last_day " . time();

        if ($file_type === 'pdf') {
            $this->ci->load->library('dompdf_lib');

            $view_data = array(
                'all_data' => $all_data,
                'branch_name' => $branch_name,
                'from_f' => $first_day_formatted,
                'to_f' => $last_day_formatted
            );

            $html = $this->ci->load->view('short_summary_pdf', $view_data, true);

            $this->ci->dompdf_lib->reset();
            $this->ci->dompdf_lib->loadHtml($html);
            $this->ci->dompdf_lib->setPaper('A4', 'landscape');
            $this->ci->dompdf_lib->render();

            $output = $this->ci->dompdf_lib->output();
            $file_name .= '.pdf';
            $file_path = $this->build_report_path('short_summary', $file_name);
            file_put_contents($file_path, $output);
        } else {
            $this->ci->load->library('excel');

            $style = array(
                'alignment' => array(
                    'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                    'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
                )
            );

            $object = new PHPExcel();
            $object->setActiveSheetIndex(0);
            $object->getDefaultStyle()->applyFromArray($style);

            $name_columns = array('Branch', 'From', 'To', 'Generated at', 'Generated by');
            $table_columns = array('Name', 'Employee ID', 'Working Days', 'Worked Days', 'Absent Days', 'Leave Days', 'Unpaid Leave Days', 'Worked Rest Days', 'Worked Holidays', 'OT', 'OT (PHx2)', 'OT (PHx3)', 'OT (RD)', 'OT (OFF)', 'Lateness Count', 'Lateness Time', 'Trips A', 'Trips B');

            $column = 0;
            foreach ($name_columns as $field) {
                $object->getActiveSheet()->setCellValueByColumnAndRow($column, 1, $field);
                $object->getActiveSheet()->getStyleByColumnAndRow($column, 1)->getFont()->setBold(true);
                $column++;
            }

            $object->getActiveSheet()->setCellValueByColumnAndRow(0, 2, $branch_name);
            $object->getActiveSheet()->setCellValueByColumnAndRow(1, 2, $first_day_formatted);
            $object->getActiveSheet()->setCellValueByColumnAndRow(2, 2, $last_day_formatted);
            $object->getActiveSheet()->setCellValueByColumnAndRow(3, 2, date('d/m/Y H:i:s'));
            $object->getActiveSheet()->setCellValueByColumnAndRow(4, 2, 'Queue Worker');

            $column = 0;
            foreach ($table_columns as $field) {
                $object->getActiveSheet()->setCellValueByColumnAndRow($column, 4, $field);
                $object->getActiveSheet()->getStyleByColumnAndRow($column, 4)->getFont()->setBold(true);
                $column++;
            }

            $row_index = 5;
            foreach ($all_data as $row_data) {
                $object->getActiveSheet()->setCellValueByColumnAndRow(0, $row_index, $row_data['employee']->first_name);
                $object->getActiveSheet()->setCellValueByColumnAndRow(1, $row_index, $row_data['employee']->special_id);
                $object->getActiveSheet()->setCellValueByColumnAndRow(2, $row_index, $row_data['working_days']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(3, $row_index, $row_data['worked_days']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row_index, $row_data['absent_days']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(5, $row_index, $row_data['paid_leaves']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(6, $row_index, $row_data['unpaid_leaves']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(7, $row_index, $row_data['worked_rest_days']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(8, $row_index, $row_data['worked_holidays']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(9, $row_index, $row_data['month_overtime_deducted']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(10, $row_index, $row_data['month_overtime_ph_x2']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(11, $row_index, $row_data['month_overtime_ph_x3']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(12, $row_index, $row_data['month_overtime_rd']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(13, $row_index, $row_data['month_overtime_off']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(14, $row_index, $row_data['late_count']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(15, $row_index, $row_data['lateness_time_deducted']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(16, $row_index, $row_data['total_trip_a']);
                $object->getActiveSheet()->setCellValueByColumnAndRow(17, $row_index, $row_data['total_trip_b']);
                $row_index++;
            }

            foreach (range('A', 'R') as $column_id) {
                $object->getActiveSheet()->getColumnDimension($column_id)->setAutoSize(true);
            }

            if ($file_type === 'xlsx') {
                $file_name .= '.xlsx';
                $object_writer = new PHPExcel_Writer_Excel2007($object);
            } else {
                $file_name .= '.xls';
                $object_writer = PHPExcel_IOFactory::createWriter($object, 'Excel5');
            }

            $file_path = $this->build_report_path('short_summary', $file_name);
            $object_writer->save($file_path);
        }

        return array(
            'status' => 'success',
            'file_path' => $file_path,
            'file_name' => $file_name,
            'summary' => array(
                'branch' => $branch_name,
                'period' => array(
                    'from' => $first_day_formatted,
                    'to' => $last_day_formatted
                ),
                'employee_count' => count($all_data),
                'file_type' => $file_type,
                'generated_at' => date('Y-m-d H:i:s'),
                'generated_by' => 'Queue Worker (Month Lock Snapshot)'
            )
        );
    }

    private function build_report_path($report_type, $file_name)
    {
        $directory = FCPATH . 'uploads/summary/monthlock/' . trim($report_type, '/\\') . '/';

        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create report directory: ' . $directory);
        }

        return $directory . $file_name;
    }
}
