<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Weekly_ot_report_handler
{
    private $load;

    public function __construct($params = array())
    {
        $CI = get_instance();
        $this->load = isset($params['load']) ? $params['load'] : $CI->load;
    }

    public function generate($all_data, $branch_name, $first_day, $last_day, $first_day_formatted, $last_day_formatted)
    {
        $files = array();

        foreach ($all_data as $entry) {
            $data = $entry;
            $data['from_f'] = $first_day_formatted;
            $data['to_f'] = $last_day_formatted;

            $this->load->library('excel');
            $object = new PHPExcel();
            $object->setActiveSheetIndex(0);
            $object->getDefaultStyle()->applyFromArray(array(
                'alignment' => array(
                    'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                    'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER
                )
            ));

            $name_columns = array('Name', 'Special ID', 'From', 'To', 'Position', 'Department', 'Generated at', 'Generated by');
            $table_columns = array('Date', 'Shift', 'Shift Work Hours', 'Actual Work Hours', 'OT', 'OT (M)', 'OT (PH)', 'OT (RD)');

            $column = 0;
            foreach ($name_columns as $field) {
                $object->getActiveSheet()->setCellValueByColumnAndRow($column, 1, $field);
                $object->getActiveSheet()->getStyleByColumnAndRow($column, 1)->getFont()->setBold(true);
                $column++;
            }

            $employee = $data['employee'];
            $object->getActiveSheet()->setCellValueByColumnAndRow(0, 2, $employee->first_name);
            $object->getActiveSheet()->setCellValueByColumnAndRow(1, 2, $employee->special_id);
            $object->getActiveSheet()->setCellValueByColumnAndRow(2, 2, $data['from_f']);
            $object->getActiveSheet()->setCellValueByColumnAndRow(3, 2, $data['to_f']);
            $object->getActiveSheet()->setCellValueByColumnAndRow(4, 2, isset($employee->position) ? $employee->position : '');
            $object->getActiveSheet()->setCellValueByColumnAndRow(5, 2, isset($employee->department) ? $employee->department : '');
            $object->getActiveSheet()->setCellValueByColumnAndRow(6, 2, date('d/m/Y H:i:s'));
            $object->getActiveSheet()->setCellValueByColumnAndRow(7, 2, 'Queue Worker');

            $column = 0;
            foreach ($table_columns as $field) {
                $object->getActiveSheet()->setCellValueByColumnAndRow($column, 4, $field);
                $object->getActiveSheet()->getStyleByColumnAndRow($column, 4)->getFont()->setBold(true);
                $column++;
            }

            $row = 5;
            foreach (isset($data['dates']) ? $data['dates'] : array() as $d) {
                $object->getActiveSheet()->setCellValueByColumnAndRow(0, $row, isset($d->date_string) ? $d->date_string : (isset($d->date) ? $d->date : ''));
                $object->getActiveSheet()->setCellValueByColumnAndRow(1, $row, isset($d->shift_name) ? $d->shift_name : '');
                $object->getActiveSheet()->setCellValueByColumnAndRow(2, $row, isset($d->shift_hours) ? $d->shift_hours : '');
                $object->getActiveSheet()->setCellValueByColumnAndRow(3, $row, isset($d->work_hours) ? $d->work_hours : '');
                $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row, isset($d->month_overtime_deducted) ? $d->month_overtime_deducted : '');
                $object->getActiveSheet()->setCellValueByColumnAndRow(5, $row, isset($d->overtime_m) ? $d->overtime_m : '');
                $object->getActiveSheet()->setCellValueByColumnAndRow(6, $row, isset($d->month_overtime_ph) ? $d->month_overtime_ph : '');
                $object->getActiveSheet()->setCellValueByColumnAndRow(7, $row, isset($d->month_overtime_rd) ? $d->month_overtime_rd : '');
                $row++;
            }

            foreach (range('A', 'S') as $columnID) {
                $object->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
            }

            $file_name = str_replace('/', '-', $employee->special_id) . ' - ' . str_replace('/', '-', $employee->first_name) . ' ' . $first_day . ' to ' . $last_day . ' - Weekly OT Summary.xlsx';
            $file_path = FCPATH . 'uploads/summary/' . $file_name;
            $writer = new PHPExcel_Writer_Excel2007($object);
            $writer->save($file_path);
            $files[] = $file_path;
        }

        if (count($files) > 1) {
            $file_name = '(' . $branch_name . ') Weekly OT Summary - ' . $first_day . ' to ' . $last_day . ' ' . time() . '.zip';
            $file_path = FCPATH . 'uploads/summary/' . $file_name;
            $zip = new ZipArchive();
            $zip->open($file_path, ZipArchive::CREATE | ZipArchive::OVERWRITE);
            foreach ($files as $file) {
                $zip->addFile($file, basename($file));
            }
            $zip->close();
        } else {
            $file_path = $files[0];
            $file_name = basename($files[0]);
        }

        return array(
            'status' => 'success',
            'file_path' => $file_path,
            'file_name' => $file_name,
            'summary' => array(
                'branch' => $branch_name,
                'period' => array(
                    'from' => $first_day_formatted,
                    'to' => $last_day_formatted
                ),
                'employee_count' => count($all_data),
                'file_type' => 'xlsx',
                'generated_at' => date('Y-m-d H:i:s'),
                'generated_by' => 'Queue Worker'
            )
        );
    }
}
