<?php
function generate_full_summary_excel($data)
{
    $style = array(
        'alignment' => array(
            'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
            'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
        )
    );

    $object = new PHPExcel();

    $object->setActiveSheetIndex(0);
    $object->getDefaultStyle()->applyFromArray($style);

    $table_columns = array("Date", "Shift", "In", "Out", "Total Hours", "Work Hours", "Break Hours", "Late Hours", "Late (Break)", "Early Out", "OT", "OT(M)", "OT(PHx2)", "OT(PHx3)", "OT(RD)", "OT(OFF)", "Days", "Trip(A)", "Trip(B)", "Late Reason", "Remark", "Staff Remark");
    $current_user = get_user();
    $cid = $current_user["company_id"];
    if ($cid == 146) {
        $table_columns = array("Date", "Shift", "In", "Out", "Total Hours", "Work Hours", "Break Hours", "Late Hours", "Late (Break)", "Early Out", "OT", "OT(M)", "OT(PHx2)", "OT(PHx3)", "OT(RD)", "OT(OFF)", "Days", "Trip(A)", "Trip(B)", "Late Reason", "Remark", "Meal Allow", "Staff Remark");
    }
    $name_columns = array("Name", "Special ID", "From", "To", "Position", "Department", "Generated at", "Generated by");

    $column = 0;

    foreach ($name_columns as $field) {
        $object->getActiveSheet()->setCellValueByColumnAndRow($column, 1, $field);
        $object->getActiveSheet()->getStyleByColumnAndRow($column, 1)->getFont()->setBold(true);

        $column++;
    }

    $object->getActiveSheet()->setCellValueByColumnAndRow(0, 2, $data["employee"]->first_name);
    $object->getActiveSheet()->setCellValueByColumnAndRow(1, 2, $data["employee"]->special_id);
    $object->getActiveSheet()->setCellValueByColumnAndRow(2, 2, $data["from_f"]);
    $object->getActiveSheet()->setCellValueByColumnAndRow(3, 2, $data["to_f"]);
    $object->getActiveSheet()->setCellValueByColumnAndRow(4, 2, $data["employee"]->position);
    $object->getActiveSheet()->setCellValueByColumnAndRow(5, 2, $data["employee"]->department);
    $object->getActiveSheet()->setCellValueByColumnAndRow(6, 2, date("d/m/Y H:i:s"));
    $object->getActiveSheet()->setCellValueByColumnAndRow(7, 2, get_user()["first_name"]);

    $column = 0;

    foreach ($table_columns as $field) {
        $object->getActiveSheet()->setCellValueByColumnAndRow($column, 4, $field);
        $object->getActiveSheet()->getStyleByColumnAndRow($column, 4)->getFont()->setBold(true);

        $column++;
    }
    $row = 5;
    foreach ($data['dates'] as $d) {
        foreach ($d->clockings as $key => $clock) {
            if ($key == 0) {
                // Check if the date is a public holiday
                $isPublicHoliday = in_array($d->date, $data["public_holidays"]);

                $object->getActiveSheet()->setCellValueByColumnAndRow(0, $row, $clock->day_f);
                if ($isPublicHoliday) {
                    $object->getActiveSheet()->getStyleByColumnAndRow(0, $row)->getFont()->setBold(true)->getColor()->setRGB('FF0000');
                } else {
                    $object->getActiveSheet()->getStyleByColumnAndRow(0, $row)->getFont()->setBold(true);
                }
                $count_clockings = count($d->clockings);
                if ($count_clockings > 1) {
                    $start_merge = $row;
                    $end_merge = $row + $count_clockings - 1;
                    $object->getActiveSheet()->mergeCells('A' . $row . ':A' . $end_merge);
                }
            }
            if (isset($clock->code) && $clock->code == 'Break') {
                $object->getActiveSheet()->setCellValueByColumnAndRow(1, $row, $clock->code);
                $object->getActiveSheet()->getStyleByColumnAndRow(1, $row)->getFont()->getColor()->setRGB('FF0000');
                $object->getActiveSheet()->setCellValueByColumnAndRow(2, $row, $clock->clock_in);
                $object->getActiveSheet()->getStyleByColumnAndRow(2, $row)->getFont()->getColor()->setRGB('FF0000');
                $object->getActiveSheet()->setCellValueByColumnAndRow(3, $row, $clock->clock_out);
                $object->getActiveSheet()->getStyleByColumnAndRow(3, $row)->getFont()->getColor()->setRGB('FF0000');
            } else {
                $object->getActiveSheet()->setCellValueByColumnAndRow(1, $row, $clock->code);
                // $clock_in_check = admin_add_edit_check_clock_in(isset($d->clockings[0]->clock_in_id) ? $d->clockings[0]->clock_in_id : null);
                $clock_in_check = admin_add_edit_check_clock_in(isset($clock->clock_in_id) ? $clock->clock_in_id : null);
                if ($clock_in_check == 1) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(2, $row, $clock->clock_in);
                    $object->getActiveSheet()->getStyleByColumnAndRow(2, $row)->getFont()->setBold(true)->getColor()->setRGB('FF0000');
                } else {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(2, $row, $clock->clock_in);
                }
                // $clock_out_check = admin_add_edit_check_clock_out(isset($d->clockings[0]->clock_out_id) ? $d->clockings[0]->clock_out_id : null);
                $clock_out_check = admin_add_edit_check_clock_out(isset($clock->clock_out_id) ? $clock->clock_out_id : null);
                if ($clock_out_check == 1) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(3, $row, $clock->clock_out);
                    $object->getActiveSheet()->getStyleByColumnAndRow(3, $row)->getFont()->setBold(true)->getColor()->setRGB('FF0000');
                } else {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(3, $row, $clock->clock_out);
                }
            }
            // $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row, $clock->total_time);
            if ($key == 0) {
                $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row, $d->total_hours);
                $object->getActiveSheet()->setCellValueByColumnAndRow(5, $row, $d->work_hours);
                $object->getActiveSheet()->setCellValueByColumnAndRow(6, $row, $d->break_hours);
                $object->getActiveSheet()->setCellValueByColumnAndRow(7, $row, $d->late_hours);
                if (!$d->is_late) {
                    $object->getActiveSheet()->getStyleByColumnAndRow(7, $row)->getFont()->setStrikethrough(true);
                }
                $object->getActiveSheet()->setCellValueByColumnAndRow(8, $row, $d->break_late_hours);
                if (!$d->is_late_break) {
                    $object->getActiveSheet()->getStyleByColumnAndRow(8, $row)->getFont()->setStrikethrough(true);
                }
                $object->getActiveSheet()->setCellValueByColumnAndRow(9, $row, $d->early_out);
                if (!$d->is_early_out) {
                    $object->getActiveSheet()->getStyleByColumnAndRow(9, $row)->getFont()->setStrikethrough(true);
                }
                // $object->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $d->short_hours);
                $ot_value = create_ot_rich_text($d);
                if (!in_array($d->date, $data["public_holidays"]) && !in_array($d->day_name, $data["rest_days"]) && $d->is_shift == 'true' && !$d->is_replaced_ph && !in_array($d->day_name, $data["off_days"]) && !$d->is_rest_day && !$d->is_employee_off_day) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $ot_value);
                }

                if ($d->x2 && (in_array($d->date, $data["public_holidays"]) || $d->is_replaced_ph)) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(12, $row, $d->overtime_ph_x2);
                }

                if ($d->x3 && (in_array($d->date, $data["public_holidays"]) || $d->is_replaced_ph)) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(13, $row, $d->overtime_ph_x3);
                }

                if (!in_array($d->date, $data["public_holidays"]) && (in_array($d->day_name, $data["rest_days"]) || $d->is_shift == 'false' || $d->is_rest_day) && !in_array($d->day_name, $data["off_days"])) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(14, $row, $ot_value);
                }

                if (!in_array($d->date, $data["public_holidays"]) && in_array($d->day_name, $data["off_days"]) || $d->is_employee_off_day) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(15, $row, $ot_value);
                }

                $object->getActiveSheet()->setCellValueByColumnAndRow(16, $row, $d->days);
                $object->getActiveSheet()->setCellValueByColumnAndRow(17, $row, $d->trip_a);
                $object->getActiveSheet()->setCellValueByColumnAndRow(18, $row, $d->trip_b);
                $object->getActiveSheet()->setCellValueByColumnAndRow(19, $row, $clock->reason);
                if ($isPublicHoliday) {
                    $public_holidays_names = $data['public_holidays_names'];
                    // print_r($public_holidays_names[array_search($d->date,$data["public_holidays"])]);die;
                    $object->getActiveSheet()->setCellValueByColumnAndRow(20, $row, $public_holidays_names[array_search($d->date, $data["public_holidays"])]);
                } else {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(20, $row, $clock->remark);
                }
                if ($cid == 146) {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(21, $row, $d->meal_days);
                    $object->getActiveSheet()->setCellValueByColumnAndRow(22, $row, $clock->staff_remark);
                } else {
                    $object->getActiveSheet()->setCellValueByColumnAndRow(21, $row, $clock->staff_remark);
                }
                $count_clockings = count($d->clockings);
                if ($count_clockings > 1) {
                    $start_merge = $row;
                    $end_merge = $row + $count_clockings - 1;
                    $object->getActiveSheet()->mergeCells('E' . $start_merge . ':E' . $end_merge);
                    $object->getActiveSheet()->mergeCells('F' . $start_merge . ':F' . $end_merge);
                    $object->getActiveSheet()->mergeCells('G' . $start_merge . ':G' . $end_merge);
                    $object->getActiveSheet()->mergeCells('H' . $start_merge . ':H' . $end_merge);
                    $object->getActiveSheet()->mergeCells('I' . $start_merge . ':I' . $end_merge);
                    $object->getActiveSheet()->mergeCells('J' . $start_merge . ':J' . $end_merge);
                    $object->getActiveSheet()->mergeCells('K' . $start_merge . ':K' . $end_merge);
                    $object->getActiveSheet()->mergeCells('L' . $start_merge . ':L' . $end_merge);
                    $object->getActiveSheet()->mergeCells('M' . $start_merge . ':M' . $end_merge);
                    $object->getActiveSheet()->mergeCells('N' . $start_merge . ':N' . $end_merge);
                    $object->getActiveSheet()->mergeCells('O' . $start_merge . ':O' . $end_merge);
                    $object->getActiveSheet()->mergeCells('P' . $start_merge . ':P' . $end_merge);
                    $object->getActiveSheet()->mergeCells('Q' . $start_merge . ':Q' . $end_merge);
                    $object->getActiveSheet()->mergeCells('R' . $start_merge . ':R' . $end_merge);
                    $object->getActiveSheet()->mergeCells('S' . $start_merge . ':S' . $end_merge);
                    $object->getActiveSheet()->mergeCells('T' . $start_merge . ':T' . $end_merge);
                    $object->getActiveSheet()->mergeCells('U' . $start_merge . ':U' . $end_merge);
                    $object->getActiveSheet()->mergeCells('V' . $start_merge . ':V' . $end_merge);
                    if ($cid == 146) {
                        $object->getActiveSheet()->mergeCells('W' . $start_merge . ':W' . $end_merge);
                    }
                }
            }
            $row++;
        }
    }
    $object->getActiveSheet()->setCellValueByColumnAndRow(0, $row, "Total");
    $object->getActiveSheet()->getStyleByColumnAndRow(0, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row, $data["total"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(4, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(5, $row, $data["work"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(5, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(6, $row, $data["break"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(6, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(7, $row, $data["late"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(7, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(8, $row, $data["break_late"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(8, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(9, $row, $data["total_early"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(9, $row)->getFont()->setBold(true);
    // $object->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $data["total_short"]);
    // $object->getActiveSheet()->getStyleByColumnAndRow(10, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $data["month_overtime"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(10, $row)->getFont()->setBold(true);
    if ($data["lateness_time"] != $data["lateness_time_deducted"]) {
        $object->getActiveSheet()->getStyleByColumnAndRow(10, $row)->getFont()->setStrikethrough(true);
    }
    $object->getActiveSheet()->setCellValueByColumnAndRow(12, $row, $data["month_overtime_ph_x2"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(12, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(13, $row, $data["month_overtime_ph_x3"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(13, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(14, $row, $data["month_overtime_rd"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(14, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(15, $row, $data["month_overtime_off"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(15, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(16, $row, $data["total_days"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(16, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(17, $row, $data["total_trip_a"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(17, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(18, $row, $data["total_trip_b"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(18, $row)->getFont()->setBold(true);
    if ($cid == 146) {
        $object->getActiveSheet()->setCellValueByColumnAndRow(21, $row, $data["total_meal_days"]);
        $object->getActiveSheet()->getStyleByColumnAndRow(21, $row)->getFont()->setBold(true);
    }
    $object->getActiveSheet()->mergeCells('A' . $row . ':D' . $row);
    $object->getActiveSheet()->mergeCells('K' . $row . ':L' . $row);
    $object->getActiveSheet()->mergeCells('T' . $row . ':U' . $row);


    $row += 2;
    $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row, "Lateness Time");
    $object->getActiveSheet()->getStyleByColumnAndRow(4, $row)->getFont()->setBold(true);
    $object->getActiveSheet()->setCellValueByColumnAndRow(7, $row, $data["lateness_time"]);
    $object->getActiveSheet()->getStyleByColumnAndRow(7, $row)->getFont()->setBold(true);
    if ($data["lateness_time"] != $data["lateness_time_deducted"]) {
        $object->getActiveSheet()->getStyleByColumnAndRow(7, $row)->getFont()->setStrikethrough(true);
    }

    $object->getActiveSheet()->mergeCells('E' . $row . ':G' . $row);
    $object->getActiveSheet()->mergeCells('H' . $row . ':J' . $row);

    if ($data["lateness_time"] != $data["lateness_time_deducted"]) {
        $row++;
        $object->getActiveSheet()->setCellValueByColumnAndRow(4, $row, "After Deduction");
        $object->getActiveSheet()->getStyleByColumnAndRow(4, $row)->getFont()->setBold(true);
        $object->getActiveSheet()->setCellValueByColumnAndRow(7, $row, $data["lateness_time_deducted"]);
        $object->getActiveSheet()->getStyleByColumnAndRow(7, $row)->getFont()->setBold(true);
        $object->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $data["month_overtime_deducted"]);
        $object->getActiveSheet()->getStyleByColumnAndRow(10, $row)->getFont()->setBold(true);
        $object->getActiveSheet()->mergeCells('E' . $row . ':G' . $row);
        $object->getActiveSheet()->mergeCells('H' . $row . ':J' . $row);
        $object->getActiveSheet()->mergeCells('K' . $row . ':L' . $row);
    }

    foreach (range('A', 'U') as $columnID) {
        $object->getActiveSheet()->getColumnDimension($columnID)
            ->setAutoSize(true);
    }

    return $object;
}
